server:
  port: 8101
spring:
  # 数据库配置
  # todo 需替换配置
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://192.168.230.100:3306/ags_search
    username: root
    password: mysql
  # Redis 配置
  # todo 需替换配置
  redis:
    database: 1
    host: 192.168.230.100
    port: 6380
    timeout: 5000
    password: redisroot
#  # Elasticsearch 配置
#  # todo 需替换配置
#  elasticsearch:
#    uris: http://localhost:9200
#    username: root
#    password: 123456